CREATE TABLE IF NOT EXISTS friendships (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  receiver_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  responded_at timestamp with time zone NULL,
  CONSTRAINT ck_friendships_distinct_users CHECK (sender_id <> receiver_id),
  CONSTRAINT uq_friendships_sender_receiver UNIQUE (sender_id, receiver_id)
);
CREATE INDEX IF NOT EXISTS ix_friendships_receiver_status ON friendships(receiver_id, status);
