CREATE TABLE IF NOT EXISTS expense_splits (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by_user_id integer NOT NULL REFERENCES users(id), paid_by_user_id integer NOT NULL REFERENCES users(id),
  description varchar(180) NOT NULL, total_amount numeric(12,2) NOT NULL CHECK (total_amount > 0), created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS split_participants (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, expense_split_id integer NOT NULL REFERENCES expense_splits(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES users(id), amount numeric(12,2) NOT NULL CHECK (amount >= 0), is_paid boolean NOT NULL DEFAULT false, paid_at timestamptz NULL,
  CONSTRAINT uq_split_participant UNIQUE (expense_split_id, user_id)
);
CREATE INDEX IF NOT EXISTS ix_split_participants_user ON split_participants(user_id);
